/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_shrimp (void)
{
  GtkWidget *shrimp;
  GtkWidget *dialog_vbox1;
  GtkWidget *table2;
  GtkWidget *label13;
  GtkWidget *current_version;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *drives_combo;
  GtkWidget *target_version;
  GtkWidget *target_partitions;
  GtkWidget *status_label;
  GtkWidget *dialog_action_area1;
  GtkWidget *close_button;
  GtkWidget *install_button;
  GtkWidget *alignment2;
  GtkWidget *hbox6;
  GtkWidget *image9;
  GtkWidget *label28;

  shrimp = gtk_dialog_new ();
  gtk_widget_set_name (shrimp, "shrimp");
  gtk_window_set_title (GTK_WINDOW (shrimp), _("Thin Client Imager"));
  gtk_window_set_type_hint (GTK_WINDOW (shrimp), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (shrimp), FALSE);

  dialog_vbox1 = GTK_DIALOG (shrimp)->vbox;
  gtk_widget_set_name (dialog_vbox1, "dialog_vbox1");
  gtk_widget_show (dialog_vbox1);

  table2 = gtk_table_new (7, 2, FALSE);
  gtk_widget_set_name (table2, "table2");
  gtk_widget_show (table2);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), table2, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (table2), 6);
  gtk_table_set_row_spacings (GTK_TABLE (table2), 6);
  gtk_table_set_col_spacings (GTK_TABLE (table2), 12);

  label13 = gtk_label_new (_("Currently Running:"));
  gtk_widget_set_name (label13, "label13");
  gtk_widget_show (label13);
  gtk_table_attach (GTK_TABLE (table2), label13, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label13), 1, 0.5);

  current_version = gtk_label_new (_("--"));
  gtk_widget_set_name (current_version, "current_version");
  gtk_widget_show (current_version);
  gtk_table_attach (GTK_TABLE (table2), current_version, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (current_version), 0, 0.5);

  label15 = gtk_label_new (_("Target:"));
  gtk_widget_set_name (label15, "label15");
  gtk_widget_show (label15);
  gtk_table_attach (GTK_TABLE (table2), label15, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label15), 1, 0.5);

  label16 = gtk_label_new (_("Version:"));
  gtk_widget_set_name (label16, "label16");
  gtk_table_attach (GTK_TABLE (table2), label16, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label16), 1, 0.5);

  label17 = gtk_label_new (_("Partitions:"));
  gtk_widget_set_name (label17, "label17");
  gtk_widget_show (label17);
  gtk_table_attach (GTK_TABLE (table2), label17, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label17), 1, 0.5);

  drives_combo = gtk_combo_box_new_text ();
  gtk_widget_set_name (drives_combo, "drives_combo");
  gtk_widget_show (drives_combo);
  gtk_table_attach (GTK_TABLE (table2), drives_combo, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  target_version = gtk_label_new (_("--"));
  gtk_widget_set_name (target_version, "target_version");
  gtk_table_attach (GTK_TABLE (table2), target_version, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (target_version), 0, 0.5);

  target_partitions = gtk_label_new (_("--"));
  gtk_widget_set_name (target_partitions, "target_partitions");
  gtk_widget_show (target_partitions);
  gtk_table_attach (GTK_TABLE (table2), target_partitions, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_line_wrap (GTK_LABEL (target_partitions), TRUE);
  gtk_misc_set_alignment (GTK_MISC (target_partitions), 0, 0.5);

  status_label = gtk_label_new (_("All data on the target device will be erased"));
  gtk_widget_set_name (status_label, "status_label");
  gtk_widget_show (status_label);
  gtk_table_attach (GTK_TABLE (table2), status_label, 0, 2, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (status_label), 0, 0.5);

  dialog_action_area1 = GTK_DIALOG (shrimp)->action_area;
  gtk_widget_set_name (dialog_action_area1, "dialog_action_area1");
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  close_button = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_set_name (close_button, "close_button");
  gtk_widget_show (close_button);
  gtk_dialog_add_action_widget (GTK_DIALOG (shrimp), close_button, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (close_button, GTK_CAN_DEFAULT);

  install_button = gtk_button_new ();
  gtk_widget_set_name (install_button, "install_button");
  gtk_widget_show (install_button);
  gtk_dialog_add_action_widget (GTK_DIALOG (shrimp), install_button, 0);
  GTK_WIDGET_SET_FLAGS (install_button, GTK_CAN_DEFAULT);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment2, "alignment2");
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (install_button), alignment2);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox6, "hbox6");
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox6);

  image9 = create_pixmap (shrimp, "system-software-installer.png");
  gtk_widget_set_name (image9, "image9");
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox6), image9, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Install Image"));
  gtk_widget_set_name (label28, "label28");
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox6), label28, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) drives_combo, "changed",
                    G_CALLBACK (on_drives_combo_changed),
                    NULL);
  g_signal_connect ((gpointer) close_button, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (shrimp, shrimp, "shrimp");
  GLADE_HOOKUP_OBJECT_NO_REF (shrimp, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (shrimp, table2, "table2");
  GLADE_HOOKUP_OBJECT (shrimp, label13, "label13");
  GLADE_HOOKUP_OBJECT (shrimp, current_version, "current_version");
  GLADE_HOOKUP_OBJECT (shrimp, label15, "label15");
  GLADE_HOOKUP_OBJECT (shrimp, label16, "label16");
  GLADE_HOOKUP_OBJECT (shrimp, label17, "label17");
  GLADE_HOOKUP_OBJECT (shrimp, drives_combo, "drives_combo");
  GLADE_HOOKUP_OBJECT (shrimp, target_version, "target_version");
  GLADE_HOOKUP_OBJECT (shrimp, target_partitions, "target_partitions");
  GLADE_HOOKUP_OBJECT (shrimp, status_label, "status_label");
  GLADE_HOOKUP_OBJECT_NO_REF (shrimp, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (shrimp, close_button, "close_button");
  GLADE_HOOKUP_OBJECT (shrimp, install_button, "install_button");
  GLADE_HOOKUP_OBJECT (shrimp, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (shrimp, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (shrimp, image9, "image9");
  GLADE_HOOKUP_OBJECT (shrimp, label28, "label28");

  return shrimp;
}

